# This is a basic workflow to help you get started with Actions

name: deploy-auth

# Controls when the workflow will run
on:
  push:
    branches:
      - master
    paths:
      - 'auth/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t olegs777/auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push olegs777/auth
      # Restart cluster in DigOcean to tell use newly pushed images
      # 1) Install doctl automaticly
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{secret.DIGITAL_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketing
      # 2) Update cluster
      - run: kubectl rollout restart deployment auth-depl
# ////
